INSERT INTO tbl_cards (hp, name, typeId, stageId, info, attack, damage, weak, resistence, retreat, cardNumberInCollection, collectionId) VALUES
(70, 'Arcanine', 1, 2, 'Fire-type evolution of Growlithe', 'Flare Blitz', '80', 'Water', 'None', '2', 59, 1),
(60, 'Butterfree', 3, 2, 'Bug and Flying Pokémon', 'Gust', '30', 'Fire', 'Fighting', '1', 12, 1),
(30, 'Weedle', 3, 1, 'Bug-type Pokémon', 'Poison Sting', '10', 'Fire', 'None', '1', 13, 1),
(100, 'Gengar', 5, 3, 'Ghost and Poison Pokémon', 'Shadow Ball', '70', 'Psychic', 'Normal', '1', 94, 1),
(50, 'Meowth', 4, 1, 'Normal-type Pokémon', 'Scratch', '20', 'Fighting', 'None', '1', 52, 1),
(40, 'Diglett', 5, 1, 'Ground-type Pokémon', 'Mud Slap', '20', 'Grass', 'Electric', '1', 50, 2),
(70, 'Dugtrio', 5, 2, 'Ground-type evolution of Diglett', 'Earthquake', '60', 'Grass', 'Electric', '2', 51, 2),
(90, 'Onix', 5, 1, 'Rock and Ground Pokémon', 'Rock Throw', '40', 'Water', 'None', '2', 95, 2),
(60, 'Zubat', 5, 1, 'Poison and Flying Pokémon', 'Bite', '20', 'Electric', 'Fighting', '1', 41, 2),
(80, 'Golbat', 5, 2, 'Evolution of Zubat', 'Wing Attack', '40', 'Electric', 'Fighting', '1', 42, 2),
(90, 'Nidoking', 5, 3, 'Ground and Poison Pokémon', 'Earth Power', '60', 'Water', 'Electric', '4', 34, 2),
(50, 'Magnemite', 4, 1, 'Electric and Steel Pokémon', 'Thunder Shock', '30', 'Fire', 'None', '1', 81, 3),
(80, 'Magneton', 4, 2, 'Evolution of Magnemite', 'Zap Cannon', '50', 'Fire', 'None', '2', 82, 3),
(100, 'Electabuzz', 4, 1, 'Electric-type Pokémon', 'Thunder Punch', '60', 'Fighting', 'None', '2', 125, 3),
(50, 'Koffing', 5, 1, 'Poison-type Pokémon', 'Sludge', '20', 'Psychic', 'Grass', '1', 109, 3),
(70, 'Weezing', 5, 2, 'Evolution of Koffing', 'Gas Bomb', '40', 'Psychic', 'Grass', '2', 110, 3),
(60, 'Rhyhorn', 5, 1, 'Ground and Rock Pokémon', 'Horn Attack', '30', 'Grass', 'Electric', '1', 111, 3),
(100, 'Rhydon', 5, 2, 'Evolution of Rhyhorn', 'Rock Slide', '70', 'Grass', 'Electric', '3', 112, 3),
(40, 'Horsea', 2, 1, 'Water-type Pokémon', 'Bubble', '10', 'Electric', 'None', '1', 116, 1),
(80, 'Seadra', 2, 2, 'Evolution of Horsea', 'Aqua Tail', '50', 'Electric', 'None', '2', 117, 1),
(90, 'Starmie', 2, 2, 'Water and Psychic Pokémon', 'Psychic Beam', '40', 'Electric', 'Psychic', '2', 121, 1),
(110, 'Dragonite', 5, 3, 'Dragon and Flying Pokémon', 'Dragon Claw', '100', 'Ice', 'None', '3', 149, 2),
(50, 'Chansey', 4, 1, 'Normal-type Pokémon', 'Soft-Boiled', '0', 'Fighting', 'None', '2', 113, 2),
(90, 'Lapras', 2, 1, 'Water and Ice Pokémon', 'Ice Beam', '60', 'Electric', 'None', '3', 131, 3),
(30, 'Jigglypuff', 4, 1, 'Normal and Fairy Pokémon', 'Sing', '0', 'Fighting', 'None', '1', 39, 3),
(60, 'Wigglytuff', 4, 2, 'Evolution of Jigglypuff', 'Double Slap', '30', 'Fighting', 'None', '2', 40, 3),
(40, 'Sandshrew', 5, 1, 'Ground-type Pokémon', 'Scratch', '20', 'Grass', 'Electric', '1', 27, 3),
(80, 'Sandslash', 5, 2, 'Evolution of Sandshrew', 'Fury Cutter', '50', 'Grass', 'Electric', '2', 28, 3),
(120, 'Golem', 5, 3, 'Rock and Ground Pokémon', 'Rock Smash', '90', 'Water', 'Electric', '4', 76, 3),
(50, 'Gastly', 5, 1, 'Ghost and Poison Pokémon', 'Lick', '10', 'Psychic', 'Normal', '1', 92, 1);
