INSERT INTO tbl_cards (hp, name, typeId, stageId, info, attack, damage, weak, resistence, retreat, cardNumberInCollection, collectionId) VALUES
(30, 'Oddish', 3, 1, 'Grass and Poison Pokémon', 'Absorb', '10', 'Fire', 'None', '1', 43, 2),
(60, 'Gloom', 3, 2, 'Evolution of Oddish', 'Acid', '20', 'Fire', 'None', '2', 44, 2),
(90, 'Vileplume', 3, 3, 'Evolution of Gloom', 'Petal Dance', '50', 'Fire', 'None', '3', 45, 2),
(40, 'Psyduck', 2, 1, 'Water-type Pokémon', 'Confusion Wave', '20', 'Electric', 'None', '1', 54, 2),
(70, 'Golduck', 2, 2, 'Evolution of Psyduck', 'Psybeam', '40', 'Electric', 'None', '2', 55, 2),
(50, 'Growlithe', 1, 1, 'Fire-type Pokémon', 'Flame Tail', '20', 'Water', 'None', '1', 58, 2),
(120, 'Kangaskhan', 4, 1, 'Normal-type Pokémon', 'Comet Punch', '40', 'Fighting', 'None', '3', 115, 2),
(80, 'Nidoqueen', 5, 3, 'Ground and Poison Pokémon', 'Mega Punch', '70', 'Water', 'Electric', '4', 31, 2),
(50, 'Poliwag', 2, 1, 'Water-type Pokémon', 'Bubble', '10', 'Electric', 'None', '1', 60, 2),
(70, 'Poliwhirl', 2, 2, 'Evolution of Poliwag', 'Water Gun', '20', 'Electric', 'None', '2', 61, 2),
(90, 'Poliwrath', 2, 3, 'Final evolution of Poliwag', 'Hydro Pump', '60', 'Electric', 'None', '3', 62, 2),
(30, 'Paras', 3, 1, 'Bug and Grass Pokémon', 'Scratch', '10', 'Fire', 'None', '1', 46, 2),
(60, 'Parasect', 3, 2, 'Evolution of Paras', 'Spore', '30', 'Fire', 'None', '2', 47, 2),
(40, 'Tentacool', 2, 1, 'Water and Poison Pokémon', 'Poison Sting', '10', 'Electric', 'Grass', '1', 72, 2),
(70, 'Tentacruel', 2, 2, 'Evolution of Tentacool', 'Hydro Splash', '40', 'Electric', 'Grass', '2', 73, 2),
(30, 'Rattata', 4, 1, 'Normal-type Pokémon', 'Bite', '10', 'Fighting', 'None', '1', 19, 3),
(55, 'Raticate', 4, 2, 'Evolution of Rattata', 'Hyper Fang', '20', 'Fighting', 'None', '2', 20, 3),
(40, 'Ekans', 5, 1, 'Poison-type Pokémon', 'Wrap', '10', 'Psychic', 'None', '1', 23, 3),
(70, 'Arbok', 5, 2, 'Evolution of Ekans', 'Sludge Bomb', '40', 'Psychic', 'None', '2', 24, 3),
(60, 'Cubone', 5, 1, 'Ground-type Pokémon', 'Bone Club', '30', 'Grass', 'Electric', '1', 104, 3),
(90, 'Marowak', 5, 2, 'Evolution of Cubone', 'Earthquake', '60', 'Grass', 'Electric', '2', 105, 3),
(60, 'Doduo', 4, 1, 'Normal and Flying Pokémon', 'Peck', '20', 'Electric', 'None', '1', 84, 3),
(80, 'Dodrio', 4, 2, 'Evolution of Doduo', 'Tri Attack', '50', 'Electric', 'None', '2', 85, 3),
(40, 'Seel', 2, 1, 'Water-type Pokémon', 'Ice Beam', '30', 'Electric', 'None', '1', 86, 3),
(80, 'Dewgong', 2, 2, 'Evolution of Seel', 'Aurora Beam', '50', 'Electric', 'None', '2', 87, 3),
(50, 'Shellder', 2, 1, 'Water-type Pokémon', 'Clamp', '20', 'Electric', 'None', '1', 90, 3),
(100, 'Cloyster', 2, 2, 'Evolution of Shellder', 'Spike Cannon', '60', 'Electric', 'None', '2', 91, 3),
(40, 'Slowpoke', 2, 1, 'Water and Psychic Pokémon', 'Headbutt', '20', 'Electric', 'Psychic', '1', 79, 3),
(80, 'Slowbro', 2, 2, 'Evolution of Slowpoke', 'Psychic', '50', 'Electric', 'Psychic', '2', 80, 3);
 